package com.health_insurance.enrollment_model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MemberRecord implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public MemberRecord() {
    }




}