package com.health_insurance.enrollment_model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Member Record")
public class MemberRecord implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Member Id")
	private java.lang.Integer id;
	@org.kie.api.definition.type.Label(value = "Date of Birth")
	private java.util.Date dateOfBirth;
	@org.kie.api.definition.type.Label(value = "Maintenance Type Code")
	private java.lang.String maintenanceTypeCode;
	@org.kie.api.definition.type.Label(value = "Task Complexity")
	private java.lang.Integer taskComplexity;

	public MemberRecord() {
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.util.Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(java.util.Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public java.lang.String getMaintenanceTypeCode() {
		return this.maintenanceTypeCode;
	}

	public void setMaintenanceTypeCode(java.lang.String maintenanceTypeCode) {
		this.maintenanceTypeCode = maintenanceTypeCode;
	}

	public java.lang.Integer getTaskComplexity() {
		return this.taskComplexity;
	}

	public void setTaskComplexity(java.lang.Integer taskComplexity) {
		this.taskComplexity = taskComplexity;
	}

	public MemberRecord(java.lang.Integer id, java.util.Date dateOfBirth,
			java.lang.String maintenanceTypeCode,
			java.lang.Integer taskComplexity) {
		this.id = id;
		this.dateOfBirth = dateOfBirth;
		this.maintenanceTypeCode = maintenanceTypeCode;
		this.taskComplexity = taskComplexity;
	}

}